version: '3'
services:
  back-end:
    build:
      context: server
    container_name: back-end
    working_dir: /usr/src/app
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    networks:
      - node-network
    ports:
      - "5000:5000"
    command: npm run start
  front-end:
    build:
      context: client
    container_name: front-end
    working_dir: /usr/src/app
    networks:
      - node-network
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "3000:3000"
    command: npm start
  nginx:
    build:
      context: nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    networks:
      - node-network
    depends_on:
      - back-end
networks:
  node-network:
    driver: bridge